# Implementations

In [2]:
import numpy as np

Yes, if you have a 1xm dimensional vector (let's call it x) and a dxm dimensional weight matrix (let's call it W), performing the matrix multiplication x * W^T results in a linear weighted combination. The transpose operation (W^T) turns the weight matrix into an mxd matrix, and multiplying it by the 1xm vector x produces a 1xd output vector.



In [34]:
x = np.array([1, 2, 3])

W = np.array(
    [[1, 2, 3], [4, 5, 6]]
)

print(
    'feature vector:',
    x, 
    'weight matrix:',
    W,
    f'vector shape: {x.shape}', 
    f'matrix shape: {W.shape}',
    sep='\n'
)

feature vector:
[1 2 3]
weight matrix:
[[1 2 3]
 [4 5 6]]
vector shape: (3,)
matrix shape: (2, 3)


In [35]:
wlc = np.matmul(x, W.T)

print(
    f'output vector (weighted linear combination): {wlc}',
    f'shape: {wlc.shape}',
    sep='\n'
)

output vector (weighted linear combination): [14 32]
shape: (2,)
